services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always
    ports:
      - "6555:5432"
    env_file:
      - ./back-end/.env.prod
    volumes:
      - drivenops-database:/var/lib/postgres/data

  drivenops_node_app:
    container_name: drivenops_node_app
    build: ./back-end
    image: drivenops_back_image
    ports:
      - "5000:5000"
    depends_on:
      - drivenops_db
    env_file:
      - ./back-end/.env.prod

  drivenops_react_app:
    container_name: drivenops_react_app
    build: ./front-end
    image: drivenops_front_image
    volumes:
      - react_server:/var/www/html

  nginx_server:
    container_name: nginx_server
    build: ./nginx
    image: nginx_server_image
    ports:
      - "80:80"
    volumes:
      - react_server:/var/www/html
    depends_on:
      - drivenops_react_app
      - drivenops_node_app
      - drivenops_db
volumes:
  drivenops-database:
  react_server:
