services:
  db:
    image: postgres
    container_name: drivenops_test_db
    restart: always
    ports:
      - "6565:5432"
    env_file:
      - .env.test

  node_app:
    container_name: drivenops_test_app
    build: .
    ports:
      - "5999:5000"
    depends_on:
      - db
    env_file:
      - .env.test
